<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\InvoiceResource;
use App\Models\Order;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

/**
 * Read-only view of the invoices generated by the service desk. An invoice is an
 * Order minted when a work order is completed (so it always carries a
 * work_order_id); storefront orders live under the separate orders endpoint.
 */
class InvoiceController extends Controller
{
    public function index(Request $request)
    {
        $invoices = Order::with('customer')
            ->whereNotNull('work_order_id')
            ->search($request->query('q'))
            ->when($request->filled('financial_status'), fn ($q) => $q->where('financial_status', $request->query('financial_status')))
            ->latest()
            ->paginate($this->perPage($request));

        return InvoiceResource::collection($invoices);
    }

    public function show(Order $invoice)
    {
        return new InvoiceResource($invoice->load(['items', 'customer']));
    }

    private function perPage(Request $request): int
    {
        return min(
            max(1, (int) $request->query('per_page', config('api.per_page', 25))),
            (int) config('api.max_per_page', 100)
        );
    }
}
